jasypt:
  encryptor:
    password: arkhyterima

management:
  endpoints:
    web:
      exposure:
        include: logfile, httptrace, auditevents, loggers, env, mappings, threaddump, metrics, info

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    stream:
      bindings:
        BlogCreationOutput:
          destination:  blog-creation
          content-type: application/json
        BlogCreationInput:
          destination:  blog-creation
          content-type: application/json
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost